{
 "title": "Elasticsearch Alerts",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "SSH Invalid user",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"journalbeat-*\" AND systemd.slice: \"system-sshd.slice\" AND message: \"Invalid user\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SSH Authentication Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"journalbeat-*\" AND systemd.slice: \"system-sshd.slice\" AND message: \"Too many authentication failures\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Squid-Main TCP_DENIED",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"journalbeat-*\" AND systemd.unit: \"squid-main.service\" AND message: \"TCP_DENIED:HIER_NONE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Squid-App TCP_DENIED",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"journalbeat-*\" AND systemd.unit: \"squid-app.service\" AND message: \"TCP_DENIED:HIER_NONE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Integrity Monitoring (/etc)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"auditbeat-*\" AND event.module: \"file_integrity\" AND file.path: \"/etc\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "File Integrity Monitoring (/usr/bin | /usr/sbin)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"auditbeat-*\" AND event.module: \"file_integrity\" AND file.path: \"bin\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Deploy History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "type": "terms",
       "field": "kubernetes.namespace",
       "id": "3",
       "fake": true,
       "settings": { "order": "desc", "size": "10", "min_doc_count": 1, "orderBy": "_term" }
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.labels.app:helm AND message:(\"updating status for updated release\")",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}