{
 "title": "App",
 "tags": [ "app" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   {
    "name": "app",
    "query": "label_values(up{kubernetes_namespace=\"$namespace\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"$app\",namespace=\"$namespace\"}) - sum(kube_deployment_spec_replicas{deployment=\"$app\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",ingress=~\"^$app.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Latency p90",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"^$app.*\"}[2m])) by (le))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Error Rate (last 2m)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",ingress=~\"^$app.*\",status=~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",ingress=~\"^$app.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU usage (2m avg)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=~\"$app-.*\",container_name!=\"POD\"}[2m])) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$app-.*\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory usage (2m avg)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=~\"^$app-.*\",container_name!=\"POD\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"^$app-.*\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"$app\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"^$app-.*\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",ingress=~\"$app\",status=~\"2..\"}[2m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",ingress=~\"$app\",status=~\"4..\"}[2m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",ingress=~\"$app\",status=~\"5..\"}[2m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"^$app.*\"}[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"^$app.*\"}[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"^$app.*\"}[2m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"^$app-.*\",container_name=\"POD\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"^$app-.*\",container_name=\"POD\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}