{
 "title": "NOC K8S",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "kube2iam failed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"filebeat-*\" AND kubernetes.container.name:kube2iam AND message:(\"*PANIC error processing request*\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tolal Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"} == 1)"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests[1m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status!~\"[4-5].*\"}[1m])) by (ingress) / sum(rate(nginx_ingress_controller_requests[1m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Upstream Request Completed Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(envoy_cluster_external_upstream_rq_completed[1m])) by (app), 0.001)",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Upstream Responses Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!~\"[4-5].*\"}[2m])) by (app) / sum(rate(envoy_cluster_upstream_rq_xx[2m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Deploy History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"filebeat-*\" AND kubernetes.labels.app:helm AND message:(\"updating status for updated release\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_index:\"filebeat-*\" AND kubernetes.labels.app:helm AND message:(\"failed install\" OR message:\"warning: Upgrade\")",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(node,status) (kube_node_status_condition{condition=\"Ready\"}) > 0"
    },
    {
     "expr": "sum by(node,label_kubernetes_io_role) (kube_node_labels{label_kubernetes_io_role=\"master\"})"
    },
    {
     "expr": "sum by(node,label_kubernetes_io_role) (kube_node_labels{label_kubernetes_io_role=\"node\"})"
    }
   ]
  },
  {
   "title": "Services No Endpoint",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by(endpoint,namespace) (kube_endpoint_address_available{endpoint!=\"cluster-autoscaler\"}) == 0"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{app=\"prometheus\",component=\"kube-state-metrics\",phase!~\"Running|Succeeded\"}) by (pod,phase,namespace) > 0"
    }
   ]
  },
  {
   "title": "Pods Restart",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{app=\"prometheus\",component=\"kube-state-metrics\"}[5m]) * 60 * 5 > 0) by (pod,namespace,container)"
    }
   ]
  }
 ]
}